# Generated by Django 3.2.6 on 2021-08-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')])),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
