# Generated by Django 3.2.6 on 2021-08-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
